package com.mmo4j.core.config

import com.typesafe.config.Config
import io.micronaut.context.annotation.Bean
import io.micronaut.context.annotation.Factory
import javax.inject.Singleton

/**
 * Implementing a factory over the creation of the WorldConfig class helps abstract out using whatever configuration
 * library of choice. In this case, we're using TypeSafe Config, but this could just as easily(is) be swapped for Micronaut
 */
@Factory
class WorldConfigFactory {
  @Bean
  @Singleton
  fun createWorld(config: Config): WorldConfig = with(config.getConfig("mmo4j.world")) {
// getDouble("").toFloat(),
    WorldConfig(
      activeWeather = getBoolean("active-weather"),
      addonChannel = getBoolean("addon-channel"),
      allFlightPaths = getBoolean("all-flight-paths"),
      allowCharacterCreation = getBoolean("allow-character-creation"),
      alwaysMaxSkillForLevel = getBoolean("always-max-skill-for-level"),
      artifactItemDropRate = getDouble("item-drop-rate.artifact").toFloat(),
      auctionCutRate = getDouble("auction.cut-rate").toFloat(),
      auctionDepositMin = getInt("auction.deposit-min"),
      auctionDepositRate = getDouble("auction.deposit-rate").toFloat(),
      auctionTimeRate = getDouble("auction.time-rate").toFloat(),
      changeWeatherInterval = getDuration("change-weather-interval"),
      charactersPerAccount = getInt("characters-per-account"),
      charactersPerRealm = getInt("characters-per-realm"),
      cleanCharacterDb = getBoolean("clean-character-db"),
      corpseDecayLootedRate = getDouble("corpse-decay-looted-rate").toFloat(),
      creatureAggroRate = getDouble("creature.aggro-rate").toFloat(),
      creatureFamilyAssistanceDelay = getInt("create-family.assistance-delay"),
      creatureFamilyAssistanceRadius = getDouble("creature-family.assistance-radius").toFloat(),
      creatureFamilyFleeAssistanceRadius = getDouble("creature-family.flee-assistance-radius").toFloat(),
      creatureFamilyFleeDelay = getInt("creature-family.flee-delay"),
      currencyAmountDropRate = getDouble("currency-amount-drop-rate").toFloat(),
      currencyDropRate = getDouble("currency-drop-rate").toFloat(),
      durabilityLossChanceAbsorb = getDouble("durability-loss-chance.absorb").toFloat(),
      durabilityLossChanceBlock = getDouble("durability-loss-chance.block").toFloat(),
      durabilityLossChanceDamage = getDouble("durability-loss-chance.damage").toFloat(),
      durabilityLossChanceParry = getDouble("durability-loss-chance.parry").toFloat(),
      eliteCreatureDamageRate = getDouble("creature.elite.damage-rate").toFloat(),
      eliteCreatureHpRate = getDouble("creature.elite.hp-rate").toFloat(),
      eliteCreatureSpellDamageRate = getDouble("creature.elite.spell-damage-rate").toFloat(),
      energyRate = getDouble("energy-rate").toFloat(),
      epicItemDropRate = getDouble("item-drop-rate.epic").toFloat(),
      expansion = getInt("expansion"),
      exploreXpRate = getDouble("explore-xp-rate").toFloat(),
      eventAnnounce = getBoolean("event-announce"),
      fallDamage = getDouble("fall-damage").toFloat(),
      focusRate = getDouble("focus-rate").toFloat(),
      gameType = getInt("game-type"),
      gridCleanupDelay = getDuration("grid-cleanup-delay"),
      gridUnload = getBoolean("grid-unload"),
      guarderSight = getDouble("guarder-sight").toFloat(),
      healthRate = getDouble("health-rate").toFloat(),
      heroicCharactersPerRealm = getInt("heroic-characters-per-realm"),
      honorRate = getDouble("honor-rate").toFloat(),
      instanceIgnoreLevel = getBoolean("instance.ignore-level"),
      instanceIgnoreRaid = getBoolean("instance.ignore-raid"),
      instanceResetInterval = getDuration("instance.reset-duration"),
      instanceResetTimeRate = getDouble("instance.reset-time-rate").toFloat(),
      instanceStrictCombatLockdown = getBoolean("instance.strict-combat-lockdown"),
      instanceUnloadDelay = getDuration("instance.unload-delay"),
      killXpRate = getDouble("kill-xp-rate").toFloat(),
      legendaryItemDropRate = getDouble("item-drop-rate.legendary").toFloat(),
      listenRangeSay = getDouble("listen-range.say").toFloat(),
      listenRangeTextEmote = getDouble("listen-range.text-emote").toFloat(),
      listenRangeYell = getDouble("listen-range.yell").toFloat(),
      longFlightPathsPersistence = getBoolean("long-flight-paths-persistence"),
      mailDeliveryDelay = getDuration("mail-delivery-delay"),
      manaRate = getDouble("mana-rate").toFloat(),
      mapUpdateInterval = getDuration("map-update-interval"),
      maxArenaPoints = getInt("max-arena-points"),
      maxGroupXpDistance = getDouble("max-group-xp-distance").toFloat(),
      maxHonorPoints = getInt("max-honor-points"),
      maxPlayerLevel = getInt("max-player-level"),
      maxPrimaryTradeSkill = getInt("max-primary-trade-skill"),
      maxWhoListReturns = getInt("max-who-list-returns"),
      minCharacterName = getInt("min-character-name"),
      minLevelForHeroicCharacterCreating = getInt("min-level-for-heroic-character-creating"),
      minPetitionSigns = getInt("min-petition-signs"),
      minPetName = getInt("min-pet-name"),
      minPlayerName = getInt("min-player-name"),
      miningAmountRate = getDouble("mining-amount-rate").toFloat(),
      miningNextRate = getDouble("mining-next-rate").toFloat(),
      moneyDropRate = getDouble("money-drop-rate").toFloat(),
      monsterSight = getDouble("monster-sight").toFloat(),
      normalCreatureDamageRate = getDouble("creature.normal.damage-rate").toFloat(),
      normalCreatureHpRate = getDouble("creature.normal.hp-rate").toFloat(),
      normalCreatureSpellDamageRate = getDouble("creature.normal.spell-damage-rate").toFloat(),
      normalItemDropRate = getDouble("item-drop-rate.normal").toFloat(),
      petXpKillRate = getDouble("pet-xp-kill-rate").toFloat(),
      playerLimit = getInt("player-limit"),
      playerSaveInterval = getDuration("player-save.interval"),
      playerSaveStatsMinLevel = getInt("player-save.stats-min-level"),
      playerSaveStatsSaveOnlyOnLogout = getBoolean("player-save.stats-save-only-on-logout"),
      poorItemDropRate = getDouble("item-drop-rate.poor").toFloat(),
      questItemDropRate = getDouble("item-drop-rate.quest").toFloat(),
      questXpRate = getDouble("quest-xp-rate").toFloat(),
      rageIncomeRate = getDouble("rage.income-rate").toFloat(),
      rageLossRate = getDouble("rage.loss-rate").toFloat(),
      rareCreatureDamageRate = getDouble("creature.rare.damage-rate").toFloat(),
      rareCreatureHpRate = getDouble("creature.rare.hp-rate").toFloat(),
      rareCreatureSpellDamageRate = getDouble("creature.rare.spell-damage-rate").toFloat(),
      rareEliteCreatureDamageRate = getDouble("creature.rare-elite.damage-rate").toFloat(),
      rareEliteCreatureHpRate = getDouble("creature.rare-elite.hp-rate").toFloat(),
      rareEliteCreatureSpellDamageRate = getDouble("rare-elite-creature-spell-damage-rate").toFloat(),
      rareItemDropRate = getDouble("item-drop-rate.rare").toFloat(),
      realmZone = getInt("realm-zone"),
      referencedItemDropRate = getDouble("item-drop-rate.referenced").toFloat(),
      reputationGainRate = getDouble("reputation-gain-rate").toFloat(),
      reputationLowLevelKillRate = getDouble("reputation-low-level-kill-rate").toFloat(),
      reputationLowLevelQuestRate = getDouble("reputation-low-level-quest-rate").toFloat(),
      restInGameRate = getDouble("rest-in-game-rate").toFloat(),
      restInWildernessRate = getDouble("rest-in-wilderness-rate").toFloat(),
      restOfflineInTavernOrCityRate = getDouble("rest-offline-in-tavern-or-city-rate").toFloat(),
      runicPowerIncomeRate = getDouble("runic-power.income-rate").toFloat(),
      runicPowerLossRate = getDouble("runic-power.loss-rate").toFloat(),
      saveRespawnTimeImmediately = getBoolean("save-respawn-time-immediately"),
      skillChanceGreen = getInt("skill-chance.green"),
      skillChanceGrey = getInt("skill-chance.grey"),
      skillChanceMilling = getBoolean("skill-chance-milling"),
      skillChanceMiningSteps = getInt("skill-chance.mining-steps"),
      skillChanceOrange = getInt("skill-chance.orange"),
      skillChanceProspecting = getBoolean("skill-chance.prospecting"),
      skillChanceSkinningSteps = getInt("skill-chance.skinning-steps"),
      skillChanceYellow = getInt("skill-chance.yellow"),
      skillFailGainFishing = getBoolean("skill-fail.gain-fishing"),
      skillFailLootFishing = getBoolean("skill-fail.loot-fishing"),
      skillGainCrafting = getInt("skill-gain.crafting"),
      skillGainDefense = getInt("skill-gain.defense"),
      skillGainGathering = getInt("skill-gain.gathering"),
      skillGainWeapon = getInt("skill-gain.weapon"),
      skillDiscoveryRate = getDouble("skill-discovery-rate").toFloat(),
      skipCinematics = getBoolean("skip-cinematics"),
      startArenaPoints = getInt("start-arena-points"),
      startHonorPoints = getInt("start-honor-points"),
      startPlayerLevel = getInt("start-player-level"),
      strictCharacterNames = getBoolean("strict-character-names"),
      strictPetNames = getBoolean("strict-pet-names"),
      strictPlayerNames = getBoolean("strict-player-names"),
      talentRate = getDouble("talent-rate").toFloat(),
      uncommonItemDropRate = getDouble("item-drop-rate.uncommon").toFloat(),
      worldBossCreatureDamageRate = getDouble("creature.world-boss.damage-rate").toFloat(),
      worldBossCreatureHpRate = getDouble("creature.world-boss.hp-rate").toFloat(),
      worldBossCreatureSpellDamageRate = getDouble("creature.world-boss.spell-damage-rate").toFloat(),
      worldBossLevelDiff = getInt("world-boss-level-diff"),
      worldServerPort = getInt("world-server-port")
    )
  }
}
